### ISSUE TITLE
Cant find language setting

### ISSUE THREAD

**Issue by Tizinais** [donvi-bz/JakesRTP#19]
Hello i have copied all settings from
https://github.com/donvi-bz/JakesRTP/blob/master/Core/src/main/resources/translations/lang_en.yml

But i could not manage to find the line for this specific one, i tried to search it but could not find it. 

"You have been teleported to Survival (cords) in Survival!"

I get this msg after getting teleported, using the command '/rtp' 
And could i disable this msg if i wanted to?

**Comment by donvi-bz** [comment]
Ah, that's because that message isn't really a stock message, but a default value to show how the `then-execute` setting works in n `RtpProfile`. Basically, you can have any in-game command run after an `rtp`, and the only command there by default shows this message. If you want to change it, by default its on line 77 of the `default-settings.yml` file located in the `rtpSettings` folder.

Also, sorry for responding so late, I realize you've likely solved this yourself by now, but this is quite a common question so I wanted to have the answer posted somewhere.
